"""File Generated by Sideko (sideko.dev)"""

from wealthtech_api.core import (
    encode_param,
    SyncBaseClient,
    default_request_options,
    to_encodable,
    RequestOptions,
    QueryParams,
    AsyncBaseClient,
)
from wealthtech_api.types.org.roi_requests.send_request import models, params
import typing


class SendRequestClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)

    # register sync api methods (keep comment for code generation)
    def create(
        self,
        *,
        data: params.PostOrgRoiRequestsSendRequestBody,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.RoiRequest:
        """
        Automatically generates and sends an email to selected Custodian in order to authorize Release of Information between Custodian and BridgeFT.
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        _json = to_encodable(
            item=data, dump_with=params._SerializerPostOrgRoiRequestsSendRequestBody
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/org/roi-requests/send-request",
            auth_names=["bearerAuth"],
            query_params=_query,
            json=_json,
            cast_to=models.RoiRequest,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncSendRequestClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)

    # register async api methods (keep comment for code generation)
    async def create(
        self,
        *,
        data: params.PostOrgRoiRequestsSendRequestBody,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.RoiRequest:
        """
        Automatically generates and sends an email to selected Custodian in order to authorize Release of Information between Custodian and BridgeFT.
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        _json = to_encodable(
            item=data, dump_with=params._SerializerPostOrgRoiRequestsSendRequestBody
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/org/roi-requests/send-request",
            auth_names=["bearerAuth"],
            query_params=_query,
            json=_json,
            cast_to=models.RoiRequest,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
