"""File Generated by Sideko (sideko.dev)"""

from wealthtech_api.core import (
    SyncBaseClient,
    QueryParams,
    AsyncBaseClient,
    RequestOptions,
    to_encodable,
    default_request_options,
    encode_param,
)
from wealthtech_api.resources.investment_management.strategies.create_many import (
    AsyncCreateManyClient,
    CreateManyClient,
)
from wealthtech_api.resources.investment_management.strategies.delete_many import (
    DeleteManyClient,
    AsyncDeleteManyClient,
)
from wealthtech_api.resources.investment_management.strategies.filter import (
    FilterClient,
    AsyncFilterClient,
)
import typing
from wealthtech_api.types.investment_management.strategies import models, params


class StrategiesClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.create_many = CreateManyClient(base_client=self._base_client)
        self.delete_many = DeleteManyClient(base_client=self._base_client)
        self.filter = FilterClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)
    def put_by_id(
        self,
        *,
        data: params.Strategy,
        id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutInvestmentManagementStrategiesIdResponse:
        """
        Provide an Investment Strategy update. Then entire Investment Strategy object **must** be provided to the `PUT` request.

        **Editable Fields:**
        - `name`
        - `description`
        - `provider`
        - `investment_minimum`
        - `fee`
        - `security_allocations`

        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerStrategy)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="PUT",
            path=f"/investment-management/strategies/{id}",
            auth_names=["bearerAuth"],
            json=_json,
            cast_to=models.PutInvestmentManagementStrategiesIdResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def put(
        self,
        *,
        data: typing.List[params.Strategy],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutInvestmentManagementStrategiesResponse:
        """
        Provide a list of Investment Strategies to update. Then entire Investment Strategy object **must** be provided to the `PUT` request.

        **Editable Fields:**
        - `name`
        - `description`
        - `provider`
        - `investment_minimum`
        - `fee`
        - `security_allocations`

        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=typing.List[params._SerializerStrategy]
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="PUT",
            path="/investment-management/strategies",
            auth_names=["bearerAuth"],
            json=_json,
            cast_to=models.PutInvestmentManagementStrategiesResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def create(
        self,
        *,
        data: params.PostInvestmentManagementStrategiesBody,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostInvestmentManagementStrategiesResponse:
        """
        Returns the created strategy
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        _json = to_encodable(
            item=data,
            dump_with=params._SerializerPostInvestmentManagementStrategiesBody,
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/investment-management/strategies",
            auth_names=["bearerAuth"],
            query_params=_query,
            json=_json,
            cast_to=models.PostInvestmentManagementStrategiesResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def get(
        self,
        *,
        id: int,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetInvestmentManagementStrategiesIdResponse:
        """
        Returns a strategy based on a single ID
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/investment-management/strategies/{id}",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.GetInvestmentManagementStrategiesIdResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def list(
        self,
        *,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetInvestmentManagementStrategiesResponse:
        """
        Returns a list of strategies within the data field
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path="/investment-management/strategies",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.GetInvestmentManagementStrategiesResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def delete(
        self,
        *,
        id: int,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.Delete:
        """
        Returns the "OK" message and a json object with the id  of item deleted, if deletion was successful
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="DELETE",
            path=f"/investment-management/strategies/{id}",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.Delete,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncStrategiesClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.create_many = AsyncCreateManyClient(base_client=self._base_client)
        self.delete_many = AsyncDeleteManyClient(base_client=self._base_client)
        self.filter = AsyncFilterClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
    async def put_by_id(
        self,
        *,
        data: params.Strategy,
        id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutInvestmentManagementStrategiesIdResponse:
        """
        Provide an Investment Strategy update. Then entire Investment Strategy object **must** be provided to the `PUT` request.

        **Editable Fields:**
        - `name`
        - `description`
        - `provider`
        - `investment_minimum`
        - `fee`
        - `security_allocations`

        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerStrategy)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="PUT",
            path=f"/investment-management/strategies/{id}",
            auth_names=["bearerAuth"],
            json=_json,
            cast_to=models.PutInvestmentManagementStrategiesIdResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def put(
        self,
        *,
        data: typing.List[params.Strategy],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutInvestmentManagementStrategiesResponse:
        """
        Provide a list of Investment Strategies to update. Then entire Investment Strategy object **must** be provided to the `PUT` request.

        **Editable Fields:**
        - `name`
        - `description`
        - `provider`
        - `investment_minimum`
        - `fee`
        - `security_allocations`

        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=typing.List[params._SerializerStrategy]
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="PUT",
            path="/investment-management/strategies",
            auth_names=["bearerAuth"],
            json=_json,
            cast_to=models.PutInvestmentManagementStrategiesResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def create(
        self,
        *,
        data: params.PostInvestmentManagementStrategiesBody,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostInvestmentManagementStrategiesResponse:
        """
        Returns the created strategy
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        _json = to_encodable(
            item=data,
            dump_with=params._SerializerPostInvestmentManagementStrategiesBody,
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/investment-management/strategies",
            auth_names=["bearerAuth"],
            query_params=_query,
            json=_json,
            cast_to=models.PostInvestmentManagementStrategiesResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def get(
        self,
        *,
        id: int,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetInvestmentManagementStrategiesIdResponse:
        """
        Returns a strategy based on a single ID
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/investment-management/strategies/{id}",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.GetInvestmentManagementStrategiesIdResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def list(
        self,
        *,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetInvestmentManagementStrategiesResponse:
        """
        Returns a list of strategies within the data field
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path="/investment-management/strategies",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.GetInvestmentManagementStrategiesResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def delete(
        self,
        *,
        id: int,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.Delete:
        """
        Returns the "OK" message and a json object with the id  of item deleted, if deletion was successful
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="DELETE",
            path=f"/investment-management/strategies/{id}",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.Delete,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
