"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PostDataSourceRealizedGainLossFilterBody(typing_extensions.TypedDict):
    """
    No description specified
    """

    abs_closed_units: typing_extensions.NotRequired[float]
    abs_closed_value: typing_extensions.NotRequired[float]
    abs_opened_units: typing_extensions.NotRequired[float]
    abs_opened_value: typing_extensions.NotRequired[float]
    account_id: typing_extensions.NotRequired[int]
    account_ids: typing_extensions.NotRequired[typing.List[int]]
    account_number: typing_extensions.NotRequired[str]
    advisor_code: typing_extensions.NotRequired[str]
    amount: typing_extensions.NotRequired[float]
    amount_long_term: typing_extensions.NotRequired[float]
    amount_short_term: typing_extensions.NotRequired[float]
    close_date: typing_extensions.NotRequired[str]
    created_at_utc: typing_extensions.NotRequired[str]
    direction: typing_extensions.NotRequired[typing_extensions.Literal["L", "S"]]
    id: typing_extensions.NotRequired[int]
    lot_identifier: typing_extensions.NotRequired[str]
    lot_selection_method: typing_extensions.NotRequired[str]
    open_date: typing_extensions.NotRequired[str]
    reported_date: typing_extensions.NotRequired[str]
    security_id: typing_extensions.NotRequired[int]
    settle_date: typing_extensions.NotRequired[str]
    source: typing_extensions.NotRequired[
        typing_extensions.Literal[
            "TIA",
            "IBK",
            "SWB",
            "EGB",
            "PER",
            "FPR",
            "NFS",
            "TDA (Available prior to Sept. 2, 2023)",
            "MLT",
            "APX",
            "DST",
        ]
    ]
    source_security_cusip: typing_extensions.NotRequired[str]
    source_security_symbol: typing_extensions.NotRequired[str]


class _SerializerPostDataSourceRealizedGainLossFilterBody(pydantic.BaseModel):
    """
    Serializer for PostDataSourceRealizedGainLossFilterBody handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    abs_closed_units: typing.Optional[float] = pydantic.Field(
        alias="abs_closed_units", default=None
    )
    abs_closed_value: typing.Optional[float] = pydantic.Field(
        alias="abs_closed_value", default=None
    )
    abs_opened_units: typing.Optional[float] = pydantic.Field(
        alias="abs_opened_units", default=None
    )
    abs_opened_value: typing.Optional[float] = pydantic.Field(
        alias="abs_opened_value", default=None
    )
    account_id: typing.Optional[int] = pydantic.Field(alias="account_id", default=None)
    account_ids: typing.Optional[typing.List[int]] = pydantic.Field(
        alias="account_ids", default=None
    )
    account_number: typing.Optional[str] = pydantic.Field(
        alias="account_number", default=None
    )
    advisor_code: typing.Optional[str] = pydantic.Field(
        alias="advisor_code", default=None
    )
    amount: typing.Optional[float] = pydantic.Field(alias="amount", default=None)
    amount_long_term: typing.Optional[float] = pydantic.Field(
        alias="amount_long_term", default=None
    )
    amount_short_term: typing.Optional[float] = pydantic.Field(
        alias="amount_short_term", default=None
    )
    close_date: typing.Optional[str] = pydantic.Field(alias="close_date", default=None)
    created_at_utc: typing.Optional[str] = pydantic.Field(
        alias="created_at_utc", default=None
    )
    direction: typing.Optional[typing_extensions.Literal["L", "S"]] = pydantic.Field(
        alias="direction", default=None
    )
    id: typing.Optional[int] = pydantic.Field(alias="id", default=None)
    lot_identifier: typing.Optional[str] = pydantic.Field(
        alias="lot_identifier", default=None
    )
    lot_selection_method: typing.Optional[str] = pydantic.Field(
        alias="lot_selection_method", default=None
    )
    open_date: typing.Optional[str] = pydantic.Field(alias="open_date", default=None)
    reported_date: typing.Optional[str] = pydantic.Field(
        alias="reported_date", default=None
    )
    security_id: typing.Optional[int] = pydantic.Field(
        alias="security_id", default=None
    )
    settle_date: typing.Optional[str] = pydantic.Field(
        alias="settle_date", default=None
    )
    source: typing.Optional[
        typing_extensions.Literal[
            "TIA",
            "FPR",
            "APX",
            "SWB",
            "TDA (Available prior to Sept. 2, 2023)",
            "DST",
            "EGB",
            "IBK",
            "NFS",
            "PER",
            "MLT",
        ]
    ] = pydantic.Field(alias="source", default=None)
    source_security_cusip: typing.Optional[str] = pydantic.Field(
        alias="source_security_cusip", default=None
    )
    source_security_symbol: typing.Optional[str] = pydantic.Field(
        alias="source_security_symbol", default=None
    )
