"""File Generated by Sideko (sideko.dev)"""

from wealthtech_api.core import (
    to_encodable,
    default_request_options,
    encode_param,
    QueryParams,
    AsyncBaseClient,
    SyncBaseClient,
    RequestOptions,
)
from wealthtech_api.resources.billing.groups.create_from_households import (
    AsyncCreateFromHouseholdsClient,
    CreateFromHouseholdsClient,
)
from wealthtech_api.resources.billing.groups.create_many import (
    CreateManyClient,
    AsyncCreateManyClient,
)
from wealthtech_api.resources.billing.groups.delete_many import (
    DeleteManyClient,
    AsyncDeleteManyClient,
)
from wealthtech_api.resources.billing.groups.filter import (
    AsyncFilterClient,
    FilterClient,
)
from wealthtech_api.resources.billing.groups.remove_assignment import (
    AsyncRemoveAssignmentClient,
    RemoveAssignmentClient,
)
import typing
from wealthtech_api.types.billing.groups import params, models


class GroupsClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.create_from_households = CreateFromHouseholdsClient(
            base_client=self._base_client
        )
        self.create_many = CreateManyClient(base_client=self._base_client)
        self.delete_many = DeleteManyClient(base_client=self._base_client)
        self.filter = FilterClient(base_client=self._base_client)
        self.remove_assignment = RemoveAssignmentClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)
    def put_by_id(
        self,
        *,
        data: params.BillingGroup,
        id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutBillingGroupsIdResponse:
        """
        Provide a billing group to update. Then entire billing group object **must** be provided to the `PUT` request.

        **Editable Fields:**
        - `name`
        - `minimum_ids`
        - `household_id`
        - `assignments`

        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerBillingGroup)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="PUT",
            path=f"/billing/groups/{id}",
            auth_names=["bearerAuth"],
            json=_json,
            cast_to=models.PutBillingGroupsIdResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def put(
        self,
        *,
        data: typing.List[params.BillingGroup],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutBillingGroupsResponse:
        """
        Provide a list of billing groups to update. Then entire billing group object **must** be provided to the `PUT` request.

        **Editable Fields:**
        - `name`
        - `minimum_ids`
        - `household_id`
        - `assignments`

        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=typing.List[params._SerializerBillingGroup]
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="PUT",
            path="/billing/groups",
            auth_names=["bearerAuth"],
            json=_json,
            cast_to=models.PutBillingGroupsResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def create(
        self,
        *,
        data: params.PostBillingGroupsBody,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostBillingGroupsResponse:
        """
        Returns the created billing group
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        _json = to_encodable(
            item=data, dump_with=params._SerializerPostBillingGroupsBody
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/billing/groups",
            auth_names=["bearerAuth"],
            query_params=_query,
            json=_json,
            cast_to=models.PostBillingGroupsResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def get(
        self,
        *,
        id: int,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetBillingGroupsIdResponse:
        """
        Returns a billing group record for a provided ID
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/billing/groups/{id}",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.GetBillingGroupsIdResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def list(
        self,
        *,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetBillingGroupsResponse:
        """
        Retrieve the enveloped list of Billing Groups
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path="/billing/groups",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.GetBillingGroupsResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def delete(
        self,
        *,
        id: int,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.Delete:
        """
        Deletes the billing group record for the provided ID.
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="DELETE",
            path=f"/billing/groups/{id}",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.Delete,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncGroupsClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.create_from_households = AsyncCreateFromHouseholdsClient(
            base_client=self._base_client
        )
        self.create_many = AsyncCreateManyClient(base_client=self._base_client)
        self.delete_many = AsyncDeleteManyClient(base_client=self._base_client)
        self.filter = AsyncFilterClient(base_client=self._base_client)
        self.remove_assignment = AsyncRemoveAssignmentClient(
            base_client=self._base_client
        )

    # register async api methods (keep comment for code generation)
    async def put_by_id(
        self,
        *,
        data: params.BillingGroup,
        id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutBillingGroupsIdResponse:
        """
        Provide a billing group to update. Then entire billing group object **must** be provided to the `PUT` request.

        **Editable Fields:**
        - `name`
        - `minimum_ids`
        - `household_id`
        - `assignments`

        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerBillingGroup)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="PUT",
            path=f"/billing/groups/{id}",
            auth_names=["bearerAuth"],
            json=_json,
            cast_to=models.PutBillingGroupsIdResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def put(
        self,
        *,
        data: typing.List[params.BillingGroup],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutBillingGroupsResponse:
        """
        Provide a list of billing groups to update. Then entire billing group object **must** be provided to the `PUT` request.

        **Editable Fields:**
        - `name`
        - `minimum_ids`
        - `household_id`
        - `assignments`

        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=typing.List[params._SerializerBillingGroup]
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="PUT",
            path="/billing/groups",
            auth_names=["bearerAuth"],
            json=_json,
            cast_to=models.PutBillingGroupsResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def create(
        self,
        *,
        data: params.PostBillingGroupsBody,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostBillingGroupsResponse:
        """
        Returns the created billing group
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        _json = to_encodable(
            item=data, dump_with=params._SerializerPostBillingGroupsBody
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/billing/groups",
            auth_names=["bearerAuth"],
            query_params=_query,
            json=_json,
            cast_to=models.PostBillingGroupsResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def get(
        self,
        *,
        id: int,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetBillingGroupsIdResponse:
        """
        Returns a billing group record for a provided ID
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/billing/groups/{id}",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.GetBillingGroupsIdResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def list(
        self,
        *,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetBillingGroupsResponse:
        """
        Retrieve the enveloped list of Billing Groups
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path="/billing/groups",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.GetBillingGroupsResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def delete(
        self,
        *,
        id: int,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.Delete:
        """
        Deletes the billing group record for the provided ID.
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="DELETE",
            path=f"/billing/groups/{id}",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.Delete,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
