"""File Generated by Sideko (sideko.dev)"""

from wealthtech_api.core import AsyncBaseClient, SyncBaseClient
from wealthtech_api.resources.data.custodian import (
    AsyncCustodianClient,
    CustodianClient,
)
from wealthtech_api.resources.data.idc import IdcClient, AsyncIdcClient
from wealthtech_api.resources.data.source import AsyncSourceClient, SourceClient


class DataClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.custodian = CustodianClient(base_client=self._base_client)
        self.idc = IdcClient(base_client=self._base_client)
        self.source = SourceClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)


class AsyncDataClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.custodian = AsyncCustodianClient(base_client=self._base_client)
        self.idc = AsyncIdcClient(base_client=self._base_client)
        self.source = AsyncSourceClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
