"""File Generated by Sideko (sideko.dev)"""

import pytest
from wealthtech_api import Client, AsyncClient
from wealthtech_api.types.reporting.web_reports import models
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_create_200_generated_success_default():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = client.reporting.web_reports.create(
        data={
            "account_id": 123,
            "end": "2022-08-31",
            "firm_id": 123,
            "household_id": 123,
            "irr_performance": False,
            "start": "2022-08-01",
            "sub_reports": [
                "account_summary",
                "consolidated_summary",
                "performance_summary",
            ],
        }
    )
    adapter = TypeAdapter(models.PostReportingWebReportsResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_create_200_generated_success_default():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = await client.reporting.web_reports.create(
        data={
            "account_id": 123,
            "end": "2022-08-31",
            "firm_id": 123,
            "household_id": 123,
            "irr_performance": False,
            "start": "2022-08-01",
            "sub_reports": [
                "account_summary",
                "consolidated_summary",
                "performance_summary",
            ],
        }
    )
    adapter = TypeAdapter(models.PostReportingWebReportsResponse)
    adapter.validate_python(response)
