"""File Generated by Sideko (sideko.dev)"""

import pytest
from wealthtech_api import AsyncClient, Client
from wealthtech_api.types.reporting.target_allocations import models
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_put_by_id_200_generated_success_default():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = client.reporting.target_allocations.put_by_id(
        id=123,
        data={
            "coefficients": [
                {
                    "class_tag_id": 123,
                    "id": 123,
                    "mac": 123,
                    "negative_tolerance": 123.45,
                    "positive_tolerance": 123.45,
                    "weight": 123.45,
                }
            ],
            "created_at_utc": "1970-01-01T00:00:00",
            "firm_id": 123,
            "id": 123,
            "name": 123,
            "slug": "string",
            "updated_at_utc": "1970-01-01T00:00:00",
        },
    )
    adapter = TypeAdapter(models.PutReportingTargetAllocationsIdResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_put_by_id_200_generated_success_default():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = await client.reporting.target_allocations.put_by_id(
        id=123,
        data={
            "coefficients": [
                {
                    "class_tag_id": 123,
                    "id": 123,
                    "mac": 123,
                    "negative_tolerance": 123.45,
                    "positive_tolerance": 123.45,
                    "weight": 123.45,
                }
            ],
            "created_at_utc": "1970-01-01T00:00:00",
            "firm_id": 123,
            "id": 123,
            "name": 123,
            "slug": "string",
            "updated_at_utc": "1970-01-01T00:00:00",
        },
    )
    adapter = TypeAdapter(models.PutReportingTargetAllocationsIdResponse)
    adapter.validate_python(response)


def test_put_200_generated_success_default():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = client.reporting.target_allocations.put(
        data=[
            {
                "coefficients": [
                    {
                        "class_tag_id": 123,
                        "id": 123,
                        "mac": 123,
                        "negative_tolerance": 123.45,
                        "positive_tolerance": 123.45,
                        "weight": 123.45,
                    }
                ],
                "created_at_utc": "1970-01-01T00:00:00",
                "firm_id": 123,
                "id": 123,
                "name": 123,
                "slug": "string",
                "updated_at_utc": "1970-01-01T00:00:00",
            }
        ]
    )
    adapter = TypeAdapter(models.PutReportingTargetAllocationsResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_put_200_generated_success_default():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = await client.reporting.target_allocations.put(
        data=[
            {
                "coefficients": [
                    {
                        "class_tag_id": 123,
                        "id": 123,
                        "mac": 123,
                        "negative_tolerance": 123.45,
                        "positive_tolerance": 123.45,
                        "weight": 123.45,
                    }
                ],
                "created_at_utc": "1970-01-01T00:00:00",
                "firm_id": 123,
                "id": 123,
                "name": 123,
                "slug": "string",
                "updated_at_utc": "1970-01-01T00:00:00",
            }
        ]
    )
    adapter = TypeAdapter(models.PutReportingTargetAllocationsResponse)
    adapter.validate_python(response)


def test_create_200_generated_success_default():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = client.reporting.target_allocations.create(
        pager_limit=123,
        pager_page=123,
        data={
            "coefficients": [
                {
                    "class_tag_id": None,
                    "mac": "EQ",
                    "negative_tolerance": 5,
                    "positive_tolerance": 5,
                    "weight": 40,
                },
                {
                    "class_tag_id": None,
                    "mac": "DT",
                    "negative_tolerance": 5,
                    "positive_tolerance": 5,
                    "weight": 50,
                },
            ],
            "firm_id": 39,
            "name": "Conservative",
            "slug": "conservative",
        },
    )
    adapter = TypeAdapter(models.PostReportingTargetAllocationsResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_create_200_generated_success_default():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = await client.reporting.target_allocations.create(
        pager_limit=123,
        pager_page=123,
        data={
            "coefficients": [
                {
                    "class_tag_id": None,
                    "mac": "EQ",
                    "negative_tolerance": 5,
                    "positive_tolerance": 5,
                    "weight": 40,
                },
                {
                    "class_tag_id": None,
                    "mac": "DT",
                    "negative_tolerance": 5,
                    "positive_tolerance": 5,
                    "weight": 50,
                },
            ],
            "firm_id": 39,
            "name": "Conservative",
            "slug": "conservative",
        },
    )
    adapter = TypeAdapter(models.PostReportingTargetAllocationsResponse)
    adapter.validate_python(response)


def test_get_200_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = client.reporting.target_allocations.get(
        id=123, pager_limit=123, pager_page=123
    )
    adapter = TypeAdapter(models.GetReportingTargetAllocationsIdResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_get_200_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = await client.reporting.target_allocations.get(
        id=123, pager_limit=123, pager_page=123
    )
    adapter = TypeAdapter(models.GetReportingTargetAllocationsIdResponse)
    adapter.validate_python(response)


def test_list_200_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = client.reporting.target_allocations.list(pager_limit=123, pager_page=123)
    adapter = TypeAdapter(models.GetReportingTargetAllocationsResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_list_200_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = await client.reporting.target_allocations.list(
        pager_limit=123, pager_page=123
    )
    adapter = TypeAdapter(models.GetReportingTargetAllocationsResponse)
    adapter.validate_python(response)


def test_delete_200_generated_success():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = client.reporting.target_allocations.delete(
        id=123, pager_limit=123, pager_page=123
    )
    adapter = TypeAdapter(models.Delete)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_delete_200_generated_success():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = await client.reporting.target_allocations.delete(
        id=123, pager_limit=123, pager_page=123
    )
    adapter = TypeAdapter(models.Delete)
    adapter.validate_python(response)
