"""File Generated by Sideko (sideko.dev)"""

import pytest
from wealthtech_api import AsyncClient, Client
from wealthtech_api.types.billing.groups.create_many import models
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_create_200_generated_success_default():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = client.billing.groups.create_many.create(
        pager_limit=123,
        pager_page=123,
        data=[
            {
                "assignments": [
                    {
                        "account_id": 230805,
                        "fee_location": 0,
                        "fee_location_option": "5",
                        "group_id": 290599,
                        "id": 642504,
                    }
                ],
                "firm_id": 39,
                "household_id": 63618,
                "minimum_ids": [123],
                "name": "John Thomas Household",
                "slug": "john-thomas-household",
            }
        ],
    )
    adapter = TypeAdapter(models.PostBillingGroupsCreateManyResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_create_200_generated_success_default():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = await client.billing.groups.create_many.create(
        pager_limit=123,
        pager_page=123,
        data=[
            {
                "assignments": [
                    {
                        "account_id": 230805,
                        "fee_location": 0,
                        "fee_location_option": "5",
                        "group_id": 290599,
                        "id": 642504,
                    }
                ],
                "firm_id": 39,
                "household_id": 63618,
                "minimum_ids": [123],
                "name": "John Thomas Household",
                "slug": "john-thomas-household",
            }
        ],
    )
    adapter = TypeAdapter(models.PostBillingGroupsCreateManyResponse)
    adapter.validate_python(response)
