"""File Generated by Sideko (sideko.dev)"""

from wealthtech_api.core import (
    RequestOptions,
    AsyncBaseClient,
    QueryParams,
    encode_param,
    to_encodable,
    SyncBaseClient,
    default_request_options,
)
from wealthtech_api.resources.billing.fee_structures.create_many import (
    AsyncCreateManyClient,
    CreateManyClient,
)
from wealthtech_api.resources.billing.fee_structures.delete_many import (
    DeleteManyClient,
    AsyncDeleteManyClient,
)
from wealthtech_api.resources.billing.fee_structures.filter import (
    FilterClient,
    AsyncFilterClient,
)
import typing
from wealthtech_api.types.billing.fee_structures import params, models


class FeeStructuresClient:
    def __init__(self, *, base_client: SyncBaseClient):
        self._base_client = base_client
        # register sync resources (keep comment for code generation)
        self.create_many = CreateManyClient(base_client=self._base_client)
        self.delete_many = DeleteManyClient(base_client=self._base_client)
        self.filter = FilterClient(base_client=self._base_client)

    # register sync api methods (keep comment for code generation)
    def put_by_id(
        self,
        *,
        data: params.FeeStructure,
        id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutBillingFeeStructuresIdResponse:
        """
        Provide a fee structure to update. Then entire fee structure object **must** be provided to the `PUT` request.

        **Editable Fields:**
        - `name`
        - `calculation_type`
        - `collection_type`
        - `frequency`
        - `quarter_cycle`
        - `balance_type`
        - `flat_rate`
        - `flat_dollar_fee`
        - `semi_annual_cycle`
        - `annual_cycle`
        - `tiers`

        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerFeeStructure)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="PUT",
            path=f"/billing/fee-structures/{id}",
            auth_names=["bearerAuth"],
            json=_json,
            cast_to=models.PutBillingFeeStructuresIdResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def put(
        self,
        *,
        data: typing.List[params.FeeStructure],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutBillingFeeStructuresResponse:
        """
        Provide a list of fee structures to update. Then entire fee structure object **must** be provided to the `PUT` request.

        **Editable Fields:**
        - `name`
        - `calculation_type`
        - `collection_type`
        - `frequency`
        - `quarter_cycle`
        - `balance_type`
        - `flat_rate`
        - `flat_dollar_fee`
        - `semi_annual_cycle`
        - `annual_cycle`
        - `tiers`

        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=typing.List[params._SerializerFeeStructure]
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="PUT",
            path="/billing/fee-structures",
            auth_names=["bearerAuth"],
            json=_json,
            cast_to=models.PutBillingFeeStructuresResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def create(
        self,
        *,
        data: params.PostBillingFeeStructuresBody,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostBillingFeeStructuresResponse:
        """
        Returns the created  Fee Structure
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        _json = to_encodable(
            item=data, dump_with=params._SerializerPostBillingFeeStructuresBody
        )
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="POST",
            path="/billing/fee-structures",
            auth_names=["bearerAuth"],
            query_params=_query,
            json=_json,
            cast_to=models.PostBillingFeeStructuresResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def get(
        self,
        *,
        id: int,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetBillingFeeStructuresIdResponse:
        """
        Returns the fee structure record for the provided ID
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path=f"/billing/fee-structures/{id}",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.GetBillingFeeStructuresIdResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def list(
        self,
        *,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetBillingFeeStructuresResponse:
        """
        Returns an enveloped list of Fee Structures.
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="GET",
            path="/billing/fee-structures",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.GetBillingFeeStructuresResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)

    def delete(
        self,
        *,
        id: int,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.Delete:
        """
        Deletes the record for the provided fee structure ID.
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send sync request (keep comment for code generation)
        return self._base_client.request(
            method="DELETE",
            path=f"/billing/fee-structures/{id}",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.Delete,
            request_options=request_options or default_request_options(),
        )
        # end -- send sync request (keep comment for code generation)


class AsyncFeeStructuresClient:
    def __init__(self, *, base_client: AsyncBaseClient):
        self._base_client = base_client
        # register async resources (keep comment for code generation)
        self.create_many = AsyncCreateManyClient(base_client=self._base_client)
        self.delete_many = AsyncDeleteManyClient(base_client=self._base_client)
        self.filter = AsyncFilterClient(base_client=self._base_client)

    # register async api methods (keep comment for code generation)
    async def put_by_id(
        self,
        *,
        data: params.FeeStructure,
        id: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutBillingFeeStructuresIdResponse:
        """
        Provide a fee structure to update. Then entire fee structure object **must** be provided to the `PUT` request.

        **Editable Fields:**
        - `name`
        - `calculation_type`
        - `collection_type`
        - `frequency`
        - `quarter_cycle`
        - `balance_type`
        - `flat_rate`
        - `flat_dollar_fee`
        - `semi_annual_cycle`
        - `annual_cycle`
        - `tiers`

        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(item=data, dump_with=params._SerializerFeeStructure)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="PUT",
            path=f"/billing/fee-structures/{id}",
            auth_names=["bearerAuth"],
            json=_json,
            cast_to=models.PutBillingFeeStructuresIdResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def put(
        self,
        *,
        data: typing.List[params.FeeStructure],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PutBillingFeeStructuresResponse:
        """
        Provide a list of fee structures to update. Then entire fee structure object **must** be provided to the `PUT` request.

        **Editable Fields:**
        - `name`
        - `calculation_type`
        - `collection_type`
        - `frequency`
        - `quarter_cycle`
        - `balance_type`
        - `flat_rate`
        - `flat_dollar_fee`
        - `semi_annual_cycle`
        - `annual_cycle`
        - `tiers`

        """
        # start -- build request data (keep comment for code generation)
        _json = to_encodable(
            item=data, dump_with=typing.List[params._SerializerFeeStructure]
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="PUT",
            path="/billing/fee-structures",
            auth_names=["bearerAuth"],
            json=_json,
            cast_to=models.PutBillingFeeStructuresResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def create(
        self,
        *,
        data: params.PostBillingFeeStructuresBody,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.PostBillingFeeStructuresResponse:
        """
        Returns the created  Fee Structure
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        _json = to_encodable(
            item=data, dump_with=params._SerializerPostBillingFeeStructuresBody
        )
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="POST",
            path="/billing/fee-structures",
            auth_names=["bearerAuth"],
            query_params=_query,
            json=_json,
            cast_to=models.PostBillingFeeStructuresResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def get(
        self,
        *,
        id: int,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetBillingFeeStructuresIdResponse:
        """
        Returns the fee structure record for the provided ID
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path=f"/billing/fee-structures/{id}",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.GetBillingFeeStructuresIdResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def list(
        self,
        *,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.GetBillingFeeStructuresResponse:
        """
        Returns an enveloped list of Fee Structures.
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="GET",
            path="/billing/fee-structures",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.GetBillingFeeStructuresResponse,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)

    async def delete(
        self,
        *,
        id: int,
        pager_limit: typing.Optional[int] = None,
        pager_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> models.Delete:
        """
        Deletes the record for the provided fee structure ID.
        """
        # start -- build request data (keep comment for code generation)
        _query: QueryParams = {}
        if pager_limit is not None:
            _query["pager.limit"] = encode_param(pager_limit, False)
        if pager_page is not None:
            _query["pager.page"] = encode_param(pager_page, False)
        # end -- build request data (keep comment for code generation)

        # start -- send async request (keep comment for code generation)
        return await self._base_client.request(
            method="DELETE",
            path=f"/billing/fee-structures/{id}",
            auth_names=["bearerAuth"],
            query_params=_query,
            cast_to=models.Delete,
            request_options=request_options or default_request_options(),
        )
        # end -- send async request (keep comment for code generation)
