"""File Generated by Sideko (sideko.dev)"""

import pytest
from wealthtech_api import AsyncClient, Client
from wealthtech_api.types.billing.invoices.filter import models
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_create_200_generated_success_default():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = client.billing.invoices.filter.create(
        pager_limit=123,
        pager_page=123,
        data={
            "annual_debit": 123.45,
            "annual_fee": 123.45,
            "billing_group_id": 123,
            "billing_report_id": 123,
            "custodian_billed_period_debit": 123.45,
            "direct_billed_period_debit": 123.45,
            "due_date": "1970-01-01T00:00:00",
            "firm_id": 123,
            "group_id": 123,
            "id": 123,
            "is_paid": True,
            "n_accounts": 123,
            "n_fee_structures": 123,
            "period_debit": 123.45,
            "snapshot_date": "1970-01-01T00:00:00",
            "total_balance": 123.45,
        },
    )
    adapter = TypeAdapter(models.PostBillingInvoicesFilterResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_create_200_generated_success_default():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = await client.billing.invoices.filter.create(
        pager_limit=123,
        pager_page=123,
        data={
            "annual_debit": 123.45,
            "annual_fee": 123.45,
            "billing_group_id": 123,
            "billing_report_id": 123,
            "custodian_billed_period_debit": 123.45,
            "direct_billed_period_debit": 123.45,
            "due_date": "1970-01-01T00:00:00",
            "firm_id": 123,
            "group_id": 123,
            "id": 123,
            "is_paid": True,
            "n_accounts": 123,
            "n_fee_structures": 123,
            "period_debit": 123.45,
            "snapshot_date": "1970-01-01T00:00:00",
            "total_balance": 123.45,
        },
    )
    adapter = TypeAdapter(models.PostBillingInvoicesFilterResponse)
    adapter.validate_python(response)
