"""File Generated by Sideko (sideko.dev)"""

from __future__ import annotations
import io
import typing
import pydantic
import typing_extensions

HttpxFile = typing.Tuple[str, typing.Union[typing.BinaryIO, io.BufferedReader]]


class PostDataIdcIndexesFilterBody(typing_extensions.TypedDict):
    """
    No description specified
    """

    cusip: typing_extensions.NotRequired[str]
    id: typing_extensions.NotRequired[int]
    internal_name: typing_extensions.NotRequired[str]
    issuer_cusip: typing_extensions.NotRequired[str]
    name: typing_extensions.NotRequired[str]
    symbol_field: typing_extensions.NotRequired[str]
    vendor_name: typing_extensions.NotRequired[str]


class _SerializerPostDataIdcIndexesFilterBody(pydantic.BaseModel):
    """
    Serializer for PostDataIdcIndexesFilterBody handling case conversions
    and file omitions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    cusip: typing.Optional[str] = pydantic.Field(alias="cusip", default=None)
    id: typing.Optional[int] = pydantic.Field(alias="id", default=None)
    internal_name: typing.Optional[str] = pydantic.Field(
        alias="internal_name", default=None
    )
    issuer_cusip: typing.Optional[str] = pydantic.Field(
        alias="issuer_cusip", default=None
    )
    name: typing.Optional[str] = pydantic.Field(alias="name", default=None)
    symbol_field: typing.Optional[str] = pydantic.Field(alias="symbol", default=None)
    vendor_name: typing.Optional[str] = pydantic.Field(
        alias="vendor_name", default=None
    )
