"""File Generated by Sideko (sideko.dev)"""

import pytest
from wealthtech_api import Client, AsyncClient
from wealthtech_api.types.investment_management.strategies.filter import models
from pydantic import TypeAdapter

# test sync & async methods (keep comment for code generation)


def test_create_200_generated_success_default():
    """Test description"""
    # tests calling sync method with example data (keep comment for code generation)
    client = Client(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = client.investment_management.strategies.filter.create(
        pager_limit=123,
        pager_page=123,
        data={
            "asset_type": "EQ",
            "benchmark_id": 11149,
            "created_at_utc": "2021-08-18T14:27:44.144798Z",
            "description": "This is a model that focuses on capital appreciation.",
            "fee": 1000,
            "firm_id": 39,
            "id": 3,
            "investment_minimum": 100000,
            "name": "Demo Strategy - Fidelity Aggressive Equity",
            "provider": "Fidelity",
            "risk_category": "AG",
            "strategy_type": "Core",
            "tax_managed": False,
            "updated_at_utc": "2021-10-13T11:34:37.614577Z",
        },
    )
    adapter = TypeAdapter(models.PostInvestmentManagementStrategiesFilterResponse)
    adapter.validate_python(response)


@pytest.mark.asyncio
async def test_await_create_200_generated_success_default():
    """Test description"""
    # tests calling async method with example data (keep comment for code generation)
    client = AsyncClient(
        username="API_USERNAME",
        password="API_PASSWORD",
        token="API_TOKEN",
        base_url="https://api.sideko.dev/v1/api_project/a9773eee-d42b-469d-a46d-faaf05e641b0/version/43ecbc55-8afa-476e-ab94-df5433a98189/mock",
    )
    response = await client.investment_management.strategies.filter.create(
        pager_limit=123,
        pager_page=123,
        data={
            "asset_type": "EQ",
            "benchmark_id": 11149,
            "created_at_utc": "2021-08-18T14:27:44.144798Z",
            "description": "This is a model that focuses on capital appreciation.",
            "fee": 1000,
            "firm_id": 39,
            "id": 3,
            "investment_minimum": 100000,
            "name": "Demo Strategy - Fidelity Aggressive Equity",
            "provider": "Fidelity",
            "risk_category": "AG",
            "strategy_type": "Core",
            "tax_managed": False,
            "updated_at_utc": "2021-10-13T11:34:37.614577Z",
        },
    )
    adapter = TypeAdapter(models.PostInvestmentManagementStrategiesFilterResponse)
    adapter.validate_python(response)
